### ISSUE TITLE
Error in if (is.null(bcfile) == FALSE & bcauto)

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#115]
I updated to zUMIs 2.4.0e. It fails right after counting is initiated with the following error:

> Counting...
> [1] "2019-03-31 16:41:18 CEST"
> Error in if (is.null(bcfile) == FALSE & bcauto) { : 
>   argument is of length zero
> Calls: cellBC
> Execution halted

Here is the yaml file I used:
```
project: MK
sequence_files:
  file1:
    name: /data/max/01_projects/04_CITE-seq/pipeline_samples/MK/fastq/MK_cDNA_R1.fastq.gz
    base_definition:
    - BC(1-16)
    - UMI(17-26)
  file2:
    name: /data/max/01_projects/04_CITE-seq/pipeline_samples/MK/fastq/MK_cDNA_R2.fastq.gz
    base_definition: cDNA(1-55)
reference:
  STAR_index: /data/max/00_reference/STAR_2.6.0c/GRCh38_no_alt_analysis_set
  GTF_file: /data/max/00_reference/gencode.v28.annotation.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/max/01_projects/04_CITE-seq/pipeline_samples/MK/zUMIs_out_hg38_no_alt_contig
num_threads: 30
mem_limit: 50
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 10
  UMI_filter:
    num_bases: 1
    phred: 10
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 0
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Counting
samtools_exec: /home/makaufm/apps/samtools_1.9/bin/samtools
pigz_exec: pigz
STAR_exec: /home/makaufm/apps/STAR_2.6.0c/bin/Linux_x86_64/STAR
zUMIs_directory: /home/makaufm/apps/zUMIs_2.4.0/zUMIs
read_layout: SE
```
Best
Max

EDIT:
I just tried to run the same sample with zUMIs 2.2.1, which I have mostly used in the past. This also fails, but with a different error:

> Counting...
> [1] "2019-03-31 17:49:02 CEST"
> Error in if (sigmasq > signif(.Machine$double.xmax, 6)) { : 
>   missing value where TRUE/FALSE needed
> Calls: cellBC ... eval -> mclustBIC -> mstep -> eval -> eval -> mstepE
> Execution halted

Any ideas what could cause this?
