### ISSUE TITLE
Stuck on 'inserting junction into the genome indices'

### ISSUE THREAD

**Issue by langkilfeather** [sdparekh/zUMIs#118]
Hi,

I am trying to process samples from a published paper. The accession provides 1 fastq file per sample, containing a UMI at the start (first 7-9 bases) followed by the cDNA read (40 bases). I inserted an artificial barcode at the start of every read of each file, and concatenated the files into one, so that it can be run with zUMIs.

I have tried running this single, concatenated fastq file and I have also tried splitting the fastq file into artifical read1 (barcode+UMI) and read2 (cDNA) files.

After finishing the 1st pass mapping, the process seems to hold permanently on 'inserting junctions into the genome indices'. There is no CPU usage (checked by htop) once at this stage. I have left the program for 4+ hours and nothing happened.

I am using zUMIS 2.4.0 and STAR 2.5.4b.

**YAML (generated from the shiny app):**
```
project: test2
sequence_files:
  file1:
    name: /mnt/storage0/share/files/bioinformatics/publicDatasets/lamanno2016/mousePostnatal/split/SRR4059937.R1.fastq.gz
    base_definition:
    - BC(1-16)
    - UMI(17-25)
  file2:
    name: /mnt/storage0/share/files/bioinformatics/publicDatasets/lamanno2016/mousePostnatal/split/SRR4059937.R2.fastq.gz
    base_definition: cDNA(3-43)
reference:
  STAR_index: /home/abc/references/mouse
  GTF_file: /home/abc/references/gencode.vM21.annotation.ERCC.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /home/abc/output
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: /home/abc/mousePostnatalWhitelist.txt
  automatic: no
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
```

**Example of my reads:**
Read1:
```
@SRR4061716.1 Run0300_BC72GGACXX_L2_T1101_C9/1
AAAGTAGAGAAGGACAAGATAGGGG
+
IIIIIIIIIIIIIIII@CBFFFFFG

```
Read2:
```
@SRR4061716.1 Run0300_BC72GGACXX_L2_T1101_C9/1
GCGCGACCTCAGATCAGACGTGGCGACCCGCTGAATTTAAGC
+
HHHHJJJJIJJJIIJJJJJHEHHFDDDDDDDDDDDDEDDEDD
```
