### ISSUE TITLE
STAR alignment failing due to short read sequence

### ISSUE THREAD

**Issue by mbassalbioinformatics** [sdparekh/zUMIs#131]
**Describe the bug**
When trying to run zUMIs on an indrop data set, the alignment step fails with an error about read length.  Ive been in contact with the developer of STAR in case it was a bug with STAR but everything seem to be ok with that.  I fed the 1st fq file which contains the reads information into STAR directly and it aligns fine.  So could it be something is trimming the read sequence inadvertently within zUMIs? Or am I configuring the yaml file incorrectly?

**To Reproduce**
YAML (paths shortened here just for ease of viewing)
```
project: indrop_HSC_donorA_SRR7665185
sequence_files:
  file1:
    name: ...SRR7665185_1.fastq.gz
    base_definition: cDNA(1-50)
  file2:
    name: ...SRR7665185_2.fastq.gz
    base_definition: BC(1-8)
  file3:
    name: ...SRR7665185_3.fastq.gz
    base_definition: BC(1-6)
  file4:
    name: ...SRR7665185_4.fastq.gz
    base_definition:
    - BC(1-8)
    - UMI(9-14)
reference:
  STAR_index: ...star_2.7_sjb49
  GTF_file: ...genes.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: .../indrop_HSC_donorA_SRR7665185
num_threads: 30
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  velocyto: yes
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /home/mbassal/tools/zUMIs2.5
read_layout: SE
```
StdOut
```
You provided these parameters:
 YAML file:	indrop_HSC_donorA_SRR7665185.yaml
 zUMIs directory:		/home/mbassal/tools/zUMIs2.5
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   0
 zUMIs version 2.5.0b 


Mon Aug  5 02:47:30 EDT 2019
Filtering...
Mon Aug  5 02:52:41 EDT 2019
[1] "3060 barcodes detected."
[1] "3115 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2019-08-05 02:52:45 EDT"
Mon Aug  5 02:56:48 EDT 2019
Counting...
[1] "2019-08-05 02:56:57 EDT"
[1] "4e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/mnt/md0/MB/analyses/bon/bon-scrnaseq/indrop_HSC_donorA_SRR7665185/indrop_HSC_donorA_SRR7665185.final_annot.gtf"
Mon Aug  5 02:57:19 EDT 2019
[1] "2019-08-05 02:57:19 EDT"
[1] "Preparing bam file for velocyto..."
[1] "2019-08-05 02:57:20 EDT"
[1] "Attempting to run RNA velocity..."
[1] "RNA velocity done!"
[1] "2019-08-05 02:57:26 EDT"
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2019-08-05 02:57:26 EDT"
Mon Aug  5 02:58:01 EDT 2019
```

Error Out
```
[W::bam_merge_core2] No @HD tag found.

EXITING because of FATAL ERROR in reads input: short read sequence line: 0
Read Name=@SRR7665185.94
Read Sequence====
DEF_readNameLengthMax=50000
DEF_readSeqLengthMax=650

Aug 05 02:56:46 ...... FATAL ERROR, exiting
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  solving row 1159861: negative widths are not allowed
Calls: .makeSAF
Execution halted
Warning message:
In fread(gtf, select = 1:2, header = F) :
  Found and resolved improper quoting in first 100 rows. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/mnt/md0/MB/analyses/bon/bon-scrnaseq/indrop_HSC_donorA_SRR7665185/zUMIs_output/expression/indrop_HSC_donorA_SRR7665185.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
```

**Desktop (please complete the following information):**
Ubuntu 16.04

Any help appreciated :)
