### ISSUE TITLE
QUESTION - ddSeq cell naming

### ISSUE THREAD

**Issue by mbassalbioinformatics** [sdparekh/zUMIs#132]
Hey,
Ive processed a ddseq dataset and just wondering how the cells are named.  The first 6 bp appear to be the 1st barcode, but I cannot figure out the remaining bases where they come from.  Are they supposed to be barcodes 2 and 3?
Thanks

**Comment by cziegenhain** [comment]
Hi, 
Cell labels are always the complete extracted barcode ranges. Since in ddseq there is a frameshift correction, the barcode should thus be from the frame-corrected BC pieces!

**Comment by mbassalbioinformatics** [comment]
Ok fair enough.  In that case what I've noticed is that the currently in the protocol specific setup on the wiki the information provided for ddSEQ is as follows
```
sequence_files:
  file1:
    name: BCUMIread_R1.fastq.gz
    base_definition:
    - BC(1-6,21-26,41-46)
    - UMI(50-57)
    correct_frameshift: TAGCCATCGCATTGC
  file2:
    name: cDNAread_R2.fastq.gz
    base_definition: cDNA(1-75)
```

When it should be
```
sequence_files:
  file1:
    name: BCUMIread_R1.fastq.gz
    base_definition:
    - BC(1-6,22-27,43-48)
    - UMI(50-57)
    correct_frameshift: TAGCCATCGCATTGC
  file2:
    name: cDNAread_R2.fastq.gz
    base_definition: cDNA(1-75)
```
The barcode positions were slightly off, thats why the naming I was seeing was not right.  
Thanks as always for the help!
