### ISSUE TITLE
Unknown erros while running zUMIs

### ISSUE THREAD

**Issue by piyushjo15** [sdparekh/zUMIs#180]
Hi Christoph.

I was trying to run zUMIs following the  instructions in the wiki. I am getting some errors, that is resulting into failure to get any alignment. 
First this is the run error report.
```
pigz: write error code 32
pigz: abort: write error on <stdout>
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
```
Now I haven't seen these errors anywhere before, so I don't know what do they mean? I am loading the modules for samtool and pigz is already in the bash profile.

As I have 10x samples that were run on multiple lanes, I concatenated R1 and R2 files and then used them as input. I also mentioned the strandness of libraries as "negatively stranded", which I assume would be the correct strandness for 10x reads.

The Read2 length is 74. However, when I look into the log report, the --sjdbOverhang parameter is being set to 0.  I don't know why is that happening? I also set cDNA to be 74. below is my yaml file.
```

project: SN175
sequence_files:
  file1:
    name: SN175_R1.fastq.gz
    base_definition:
    - BC(1-16)
    - UMI(7-28)
  file2:
    name: SN175_R2.fastq.gz
    base_definition: cDNA(74)
reference:
  STAR_index: /home/p541i/HB/index/stargencdH38_nogtf
  GTF_file: /home/p541i/HB/ann/gencdH38p13r33CR.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /home/p541i/DATA/zUMIsout
num_threads: 20
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: /home/p541i/HB/ann/3M-february-2018.txt
  automatic: no
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 2
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
zUMIs_directory: /home/p541i/zUMIs

```
