### ISSUE TITLE
Test run issue

### ISSUE THREAD

**Issue by Ariunaa5000** [sdparekh/zUMIs#184]
Hello, 

I am trying to run the test data with zUMI. But I have been getting errors. 

The following is my yaml file set up. 
```
project: test2
sequence_files:
  file1:
    name: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/barcoderead_HEK.1mio.fq
    base_definition:
    - cDNA(17-50)
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/cDNAread_HEK.1mio.fq
    base_definition: cDNA(1-50)
reference:
  STAR_index: /gpfs0/home/gdlessnicklab/share/trails/genomes/hg19_STARindex
  GTF_file: /gpfs0/home/gdlessnicklab/lab/hg19/gencode.v19.annotation.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
zUMIs_directory: /gpfs0/home/gdlessnicklab/rsaxb003/Downloads/zUMIs
read_layout: PE
```
Ant the latest error I am getting is: 
```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)


 You provided these parameters:
 YAML file:     test2.yaml
 zUMIs directory:               /gpfs0/home/gdlessnicklab/rsaxb003/Downloads/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   0
 zUMIs version 2.8.0


Mon May 11 15:30:21 Local time zone must be set--see zic manual page 2020
WARNING: The STAR version used for mapping is 2.7.0f_0328 and the STAR index was created using the version 20201. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.0f_0328.
Filtering...
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
split: unrecognized option '--filter=pigz -p 8 > $FILE.gz'
Try `split --help' for more information.
split: unrecognized option '--filter=pigz -p 8 > $FILE.gz'
Try `split --help' for more information.
ls: cannot access /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge/cDNAread_HEK.1mio.fqtest2*: No such file or directory
ls: cannot access /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge/barcoderead_HEK.1mio.fqtest2*: No such file or directory
ls: cannot access /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge/barcoderead_HEK.1mio.fq*: No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
ls: cannot access /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge//test2.*.filtered.tagged.bam: No such file or directory
cat: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge//test2.*.BCstats.txt: No such file or directory
rm: cannot remove `/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge/barcoderead_HEK.1mio.fq*gz': No such file or directory
rm: cannot remove `/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge/cDNAread_HEK.1mio.fq*gz': No such file or directory
Mon May 11 15:30:22 Local time zone must be set--see zic manual page 2020
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
WARNING: ignoring environment value of R_HOME
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Error in eval(bysub, parent.frame(), parent.frame()) :
  object 'XC' not found
Calls: cellBC -> [ -> [.data.table -> eval -> eval
In addition: Warning message:
In data.table::fread(bccount_file, header = FALSE, col.names = c("XC",  :
  File '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/test2.BCstats.txt' has size 0. Returning a NULL data.table.
Execution halted
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Mapping...
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
WARNING: ignoring environment value of R_HOME
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
[1] "2020-05-11 15:30:28 Local time zone must be set--see zic manual page"
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
cp: cannot open `/gpfs0/home/gdlessnicklab/lab/hg19/gencode.v19.annotation.gtf' for reading: Permission denied
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[E::hts_open_format] Failed to open file NA
samtools view: failed to open "NA" for reading: No such file or directory
Warning message:
In data.table::fread(paste(samtools, "view", filtered_bams[1], "| cut -f10 | head -n 1000"),  :
  File '/tmp/Rtmp12vjkH/file66e26400e2d' has size 0. Returning a NULL data.table.
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Usage: samtools cat [options] <in1.bam>  [... <inN.bam>]
       samtools cat [options] <in1.cram> [... <inN.cram>]

Concatenate BAM or CRAM files, first those in <bamlist.fofn>, then those
on the command line.

Options: -b FILE  list of input BAM/CRAM file names, one per line
         -h FILE  copy the header from FILE [default is 1st input file]
         -o FILE  output BAM/CRAM

EXITING: FATAL INPUT ERROR: empty value for parameter "readFilesIn" in input "Command-Line"
SOLUTION: use non-empty value for this parameter

May 11 11:30:28 ...... FATAL ERROR, exiting
sh: line 1: 26354 Done(102)               STAR --readFilesCommand samtools view -@ 1 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype SAM --outStd SAM --genomeDir /gpfs0/home/gdlessnicklab/share/trails/genomes/hg19_STARindex --sjdbGTFfile /gpfs0/home/gdlessnicklab/lab/hg19/gencode.v19.annotation.gtf --runThreadN 5 --readFilesIn --outFileNamePrefix /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/test2.filtered.tagged. --sjdbOverhang NA --readFilesType SAM PE --twopassMode Basic
     26355 Segmentation fault      (core dumped) | samtools view -@ 2 -o /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/test2.filtered.tagged.Aligned.out.bam
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Mon May 11 15:30:28 Local time zone must be set--see zic manual page 2020
Counting...
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
WARNING: ignoring environment value of R_HOME
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[1] "2020-05-11 15:30:39 Local time zone must be set--see zic manual page"
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) :
  File '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/test2kept_barcodes.txt' does not exist or is non-readable. getwd()=='/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI'
Execution halted
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Mon May 11 15:30:39 Local time zone must be set--see zic manual page 2020
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
WARNING: ignoring environment value of R_HOME
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'loomR'
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/expression/test2.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Mon May 11 15:30:50 Local time zone must be set--see zic manual page 2020
Descriptive statistics...
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
WARNING: ignoring environment value of R_HOME
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
[1] "I am loading useful packages for plotting..."
[1] "2020-05-11 15:30:52 Local time zone must be set--see zic manual page"
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Error in fread(gtf, select = 1:2, header = F) :
  File '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/test2.final_annot.gtf' does not exist or is non-readable. getwd()=='/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI'
Calls: getUserSeq -> fread
Execution halted
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Mon May 11 15:30:58 Local time zone must be set--see zic manual page 2020
```
Any suggestions on why I am getting this error would be helpful. Thanks so much. 

Ariunaa

**Comment by cziegenhain** [comment]
Hi Ariunaa,

Which OS are you running zUMIs on?

Some question on your YAML file (likely unrelated to the errors):
- Is this this the zUMIs test data that comes with zUMIs? If yes, why did you give ` - cDNA(17-50)` in read1? The read1 only contains BC & UMI. You should avoid giving a base range that does not exist in the reads.

**Comment by Ariunaa5000** [comment]
Hi Christoph, 

I am trying to run it on Linux. I think I got the locale issue resolved by unloading glibc. Turns out that was being loaded when I loaded STAR. I am still getting errors running the test file though. 

For the test file, I didn't realize it was BC and UMI were the only info in that file. I will remove those promptly.

**Comment by cziegenhain** [comment]
Hi,

I was hoping you could be a bit more specific (which distribution & version?). The error reads odd to me, as `split` is a very basic unix command.
Are the paths to the fastq files correct? Also, could you try them gzipped (as provided in the git repository?)

**Comment by Ariunaa5000** [comment]
Hi again, 

So I talked to the people who run our cluster. And they identified that old version of split was being used. I updated that and ran into a different problem. 

```
You provided these parameters:
 YAML file:     test3.yaml
 zUMIs directory:               /gpfs0/home/gdlessnicklab/rsaxb003/Downloads/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   0
 zUMIs version 2.8.0


Wed May 13 13:23:42 EDT 2020
WARNING: The STAR version used for mapping is 2.7.0f_0328 and the STAR index was created using the version 2.7.0d. This may lead to an error while mapping. If you encounter                                                               any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.0f_0328.
Filtering...
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3af.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3ae.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3ab.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3ag.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3ac.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3ad.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3ah.filtered.tagged.bam'
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3ai.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-6);UMI(7-16) cDNA(1-50)/zUMIs_output/.tmpMerge//gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI.test3aa.filtered.tagged.bam'
ls: cannot access '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge//test3.*.filtered.tagged.bam': No such file or directory
cat: '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/.tmpMerge//test3.*.BCstats.txt': No such file or directory
Wed May 13 13:24:18 EDT 2020
WARNING: ignoring environment value of R_HOME
Error in eval(bysub, parent.frame(), parent.frame()) :
  object 'XC' not found
Calls: cellBC -> [ -> [.data.table -> eval -> eval
In addition: Warning message:
In data.table::fread(bccount_file, header = FALSE, col.names = c("XC",  :
  File '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/test3.BCstats.txt' has size 0. Returning a NULL data.table.
Execution halted
Mapping...
WARNING: ignoring environment value of R_HOME
[1] "2020-05-13 13:24:20 EDT"
cp: cannot open '/gpfs0/home/gdlessnicklab/lab/hg19/gencode.v19.annotation.gtf' for reading: Permission denied
[E::hts_open_format] Failed to open file NA
samtools view: failed to open "NA" for reading: No such file or directory
Warning message:
In data.table::fread(paste(samtools, "view", filtered_bams[1], "| cut -f10 | head -n 1000"),  :
  File '/tmp/RtmpK10Hgs/file37feee9c0a6' has size 0. Returning a NULL data.table.
Usage: samtools cat [options] <in1.bam>  [... <inN.bam>]
       samtools cat [options] <in1.cram> [... <inN.cram>]

Concatenate BAM or CRAM files, first those in <bamlist.fofn>, then those
on the command line.

Options: -b FILE  list of input BAM/CRAM file names, one per line
         -h FILE  copy the header from FILE [default is 1st input file]
         -o FILE  output BAM/CRAM

EXITING: FATAL INPUT ERROR: empty value for parameter "readFilesIn" in input "Command-Line"
SOLUTION: use non-empty value for this parameter

May 13 13:24:20 ...... FATAL ERROR, exiting
Wed May 13 13:24:20 EDT 2020
Counting...
WARNING: ignoring environment value of R_HOME
[1] "2020-05-13 13:24:27 EDT"
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) :
  File '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/test3kept_barcodes.txt' does not exist or is non-readable. getwd()=='/gpfs0/home/gdlessnicklab/rsaxb003/Te                                                              st_zUMI'
Execution halted
Wed May 13 13:24:28 EDT 2020
WARNING: ignoring environment value of R_HOME
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘loomR’
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/zUMIs_output/expression/test3.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Wed May 13 13:24:31 EDT 2020
Descriptive statistics...
WARNING: ignoring environment value of R_HOME
[1] "I am loading useful packages for plotting..."
[1] "2020-05-13 13:24:31 EDT"
Error in fread(gtf, select = 1:2, header = F) :
  File '/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/test3.final_annot.gtf' does not exist or is non-readable. getwd()=='/gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI'
Calls: getUserSeq -> fread
Execution halted
Wed May 13 13:24:34 EDT 2020
```

The version is - Linux 2.6.32-696.30.1.el6.x86_64 x86_64
The dist info - 
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)
Release:        6.9
Codename:       Final


Ariunaa

**Comment by cziegenhain** [comment]
can you upload your YAML exactly again? It looks like there is a problem in the formatting, because the file names contain `BC(1-6);UMI(7-16) cDNA(1-50)`!

**Comment by Ariunaa5000** [comment]
Sure. I used the Shiny app to create this. 

```
project: test2
sequence_files:
  file1:
    name: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/barcoderead_HEK.1mio.fq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/cDNAread_HEK.1mio.fq.gz
    base_definition: 
	- cDNA(1-50)
reference:
  STAR_index: /gpfs0/home/gdlessnicklab/rsaxb003/hg19/hg_19_STAR_Index
  GTF_file: /gpfs0/home/gdlessnicklab/lab/hg19/gencode.v19.annotation.gtf
  additional_STAR_params: ~
  additional_files: ~
out_dir: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
zUMIs_directory: /gpfs0/home/gdlessnicklab/rsaxb003/Downloads/zUMIs
```

**Comment by Ariunaa5000** [comment]
Sure. I used the Shiny app to create this file. 

```
project: test3
sequence_files:
  file1:
    name: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/barcoderead_HEK.1mio.fq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI/cDNAread_HEK.1mio.fq.gz
    base_definition: cDNA(1-50)
reference:
  STAR_index: /gpfs0/home/gdlessnicklab/rsaxb003/hg19/hg_19_STAR_Index
  GTF_file: /gpfs0/home/gdlessnicklab/lab/hg19/gencode.v19.annotation.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /gpfs0/home/gdlessnicklab/rsaxb003/Test_zUMI
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /gpfs0/home/gdlessnicklab/rsaxb003/Downloads/zUMIs
read_layout: PE
```
