### ISSUE TITLE
Counting failure : Error in gsub

### ISSUE THREAD

**Issue by HealHer** [sdparekh/zUMIs#188]
Hi, 

First of all thank you very much for zUMIs. I use it to re-processed public data in order to apply additional quality control. The error occurs when trying to processed the SRP218975 [(GSE136103)](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE136103). 

I work on ubuntu (on EC2 instance). I downloaded the fastq files with sra-toolkit, concatenate the experiments and launch zUMIs with the yaml I created. The protocol used for this experiment is the single-cell is Chromium 3' V2 (provided by 10x) 

This is the YAML I give : 
```
###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project: 86

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /home/ubuntu/SRX6747675_R2.fastq.gz
    base_definition:
      - BC(1-16)
      - UMI(17-26)
  file2:
    name:  /home/ubuntu/SRX6747675_R3.fastq.gz
    base_definition:
      - cDNA(1-75)


#reference genome setup
reference:
  STAR_index: /home/ubuntu/STAR_indexLength_74
  GTF_file: /home/ubuntu/AnnotatedGenome_1.gtf
  additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params: --limitSjdbInsertNsj 2000000 --limitOutSJcollapsed 5000000

#output directory
out_dir: /home/ubuntu/Alignment

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 32
mem_limit: null #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  automatic: yes #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 100 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  write_ham: no #If hamming distance collapse of UMI sequences is performed, write out mapping tables & UB corrected bam files.
  velocyto: no #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: no


#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths
samtools_exec: samtools #samtools executable
Rscript_exec: Rscript #Rscript executable
STAR_exec: STAR #STAR executable
pigz_exec: pigz #pigz executable

#below, fqfilter will add a read_layout flag defining SE or PE
zUMIs_directory: /home/ubuntu/zUMIs
read_layout: SE
```

and this is the complete Counting feed with the command
./zUMIs-master.sh -y /home/ubuntu/86.yaml

 ```
You provided these parameters:
 YAML file:     /home/ubuntu/86.yaml
 zUMIs directory:               /home/ubuntu/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   null
 zUMIs version 2.8.0 


Fri May 15 08:35:06 UTC 2020
WARNING: The STAR version used for mapping is 2.5.4b and the STAR index was created using the version 20201. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.5.4b.
Counting...
[1] "2020-05-15 08:35:14 UTC"
[1] "4.5e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/ubuntu/Alignment/86.final_annot.gtf"
Error in gsub("SN:", "", chr) : object 'chr' not found
Calls: .makeSAF ... .chromLengthFilter -> [ -> [.data.table -> eval -> eval -> gsub
In addition: Warning message:
In data.table::fread(bread, col.names = c("chr", "len"), header = F) :
  File '/tmp/RtmpBiyrJL/file76eb64421df3' has size 0. Returning a NULL data.table.
Execution halted
Fri May 15 08:35:34 UTC 2020
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘loomR’
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/ubuntu/Alignment/zUMIs_output/expression/86.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Fri May 15 08:35:35 UTC 2020
Fri May 15 08:35:35 UTC 2020
```

I only give you the Counting part because, the last try I did mentionned that plyranges was not installed on R. I manage to install it via BioConductor and then re-start zUMIs from the Counting step. (below attach the feed form the previous run)
```
 You provided these parameters:
 YAML file:     /home/ubuntu/MultiOmic_Pipeline/Data/SourceRunTable/YAML/86.yaml
 zUMIs directory:               /home/ubuntu/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   null
 zUMIs version 2.8.0 


Fri May 15 07:28:50 UTC 2020
WARNING: The STAR version used for mapping is 2.5.4b and the STAR index was created using the version 20201. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.5.4b.
Filtering...
Fri May 15 08:01:54 UTC 2020
[1] "7550 barcodes detected."
[1] "7622768 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Found 2423 daughter barcodes that can be binned into 1736 parent barcodes."
[1] "Binned barcodes correspond to 410961 reads."
Mapping...
[1] "2020-05-15 08:08:59 UTC"        Fri May 15 08:32:08 UTC 2020  
Counting...
[1] "2020-05-15 08:32:17 UTC"
[1] "4.5e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/ubuntu/Alignment/86.final_annot.gtf"
Error in loadNamespace(name) : there is no package called ‘plyranges’
Calls: .makeSAF ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Fri May 15 08:32:17 UTC 2020
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘loomR’
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/ubuntu/Alignment/zUMIs_output/expression/86.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Fri May 15 08:32:18 UTC 2020
Fri May 15 08:32:18 UTC 2020
```

Thank you for your time, 
Alexis
