### ISSUE TITLE
Still can't reproduce results (Fibroblast data from Smart-seq3 paper)

### ISSUE THREAD

**Issue by gringer** [sdparekh/zUMIs#199]
I'm still having numerous issues with the fibroblast data from the [Smart-seq3 paper](https://doi.org/10.1038/s41587-020-0497-0), downloaded via [ArrayExpress](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-8735/). I figured I might as well write an issue specifically for this general problem, as it will help provide a landing spot to highlight any associated issues.

**Current Status**

In order to save a bit of time, I am working with a 1M read subset of the data. Note that due to fetch / pull times, and my availability to devote time to this, there may be some delay between fixes being implemented in the code, and things working for me.

First error: just after barcodes have been counted and matched up. (about 1 minute into the run) ***[I would like zUMIs to stop here, rather than acting like everything's good enough to continue]***

zUMIs halt point: just after loading packages for plotting

Other indications that there are problems with input / output:

    ## After "Mapping..."
    cut: write error: Broken pipe
    EXITING: because of fatal INPUT file error: could not open read file: NA
    SOLUTION: check that this file exists and has read permision.
    Jul 16 17:23:42 ...... FATAL ERROR, exiting
    ## After STAR "inserting junctions into the genome indices"
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.2._STARtmp//readFilesIn.info: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.2._STARtmp//readFilesIn.info: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.2._STARtmp/tmp.fifo.header: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.2._STARtmp/tmp.fifo.header: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.2._STARtmp/tmp.fifo.header: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.2._STARtmp/tmp.fifo.header: Directory nonexistent
    ## After STAR "finished successfully"
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.5._STARtmp//readFilesIn.info: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.5._STARtmp//readFilesIn.info: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.5._STARtmp/tmp.fifo.header: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.5._STARtmp/tmp.fifo.header: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.5._STARtmp/tmp.fifo.header: Directory nonexistent
    sh: 1: cannot create /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.5._STARtmp/tmp.fifo.header: Directory nonexistent
    ## After all STAR processes finished (about 8 hours in)
    [W::bam_hdr_read] EOF marker is absent. The input is probably truncated
    [E::bam_hdr_read] Invalid BAM binary header
    [bam_cat] ERROR: couldn't read header for '/mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/.tmpMap//tmp.zUMI_1M_Fibroblasts_test11.6.Aligned.out.bam'.
    ## After RSubread information page /  Hamming distance collapse (about 8 hours in)
    Error in .checkTypos(e, names_x) : Object 'GEin' not found amongst ftype
    Calls: reads2genes_new ... tryCatchList -> tryCatchOne -> <Anonymous> -> .checkTypos
    Execution halted
    ## After installing loomR
    Error in gzfile(file, "rb") : cannot open the connection
    Calls: rds_to_loom -> readRDS -> gzfile
    In addition: Warning message:
    In gzfile(file, "rb") :
      cannot open compressed file '/mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/expression/zUMI_1M_Fibroblasts_test11.dgecounts.rds', probable reason 'No such file or directory'
    Execution halted
    ## After loading useful packages for plotting (about 8.25 hours in)
    Error in gzfile(file, "rb") : cannot open the connection
    Calls: readRDS -> gzfile
    In addition: Warning message:
    In gzfile(file, "rb") :
      cannot open compressed file '/mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11/zUMIs_output/expression/zUMI_1M_Fibroblasts_test11.dgecounts.rds', probable reason 'No such file or directory'
    Execution halted

**YAML file**

*[please note: if there are any issues with this, it's important that they be checked by the code, and force a halt (where not recoverable), prior to starting the bulk of the zUMIs run]*

```
project: zUMI_1M_Fibroblasts_test11
out_dir: /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/zUMI_run11
sequence_files:
  file1:
    name: /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/1M_Smartseq3.Fibroblasts.NovaSeq.R1.fastq.gz
    base_definition:
    - cDNA(1-150)
    - UMI(12-19)
    find_pattern: ATTGCGCAATG
  file2:
    name: /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/1M_Smartseq3.Fibroblasts.NovaSeq.R2.fastq.gz
    base_definition:
    - cDNA(1-150)
  file3:
    name: /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/1M_Smartseq3.Fibroblasts.NovaSeq.I1.fastq.gz
    base_definition:
    - BC(1-8)
  file4:
    name: /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/1M_Smartseq3.Fibroblasts.NovaSeq.I2.fastq.gz
    base_definition:
    - BC(1-8)
reference:
  STAR_index: /mnt/ufds/STAR/mm10_v100_2.7.5a
  GTF_file: /home/gringer/db/fasta/mmus/ensembl/v100/Mus_musculus.GRCm38.100.gtf
  additional_STAR_params: --limitSjdbInsertNsj 2000000 --outFilterIntronMotifs RemoveNoncanonicalUnannotated
    --clip3pAdapterSeq CTGTCTCTTATACACATCT
  additional_files: ~
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 2
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: /mnt/BigBirdStornext/Scratch/public_data/Illumina/Smart-Seq3/annotation/expected_barcodes.txt
  automatic: no
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: no
num_threads: 10
mem_limit: 0
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
zUMIs_directory: /home/gringer/install/zUMIs
read_layout: SE
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: /home/gringer/bin/STAR
Rscript_exec: Rscript

```

**Other potentially useful information**

My working directory is mounted as a sshfs on a Debian Linux computer.

    $ head expected_barcodes.txt
    BC
    TGTGCCTTAACCGCAA
    CGCAAGAAAACCGCAA
    GACTGTGTAACCGCAA
    TCGTAGACAACCGCAA
    TTACCTGCAACCGCAA
    TCCGTAAGAACCGCAA
    TTGTCGTGAACCGCAA
    TACCGTCTAACCGCAA
    ACAGGAGAAACCGCAA

**Conclusion**

I'm still struggling for zUMIs to generate *any* results, let alone produce results that are similar to those in the paper.

**Comment by cziegenhain** [comment]
Hi,

I think it's a good idea to test on a small dataset with 1 mio reads.

- From your log file I would think that maybe the STAR output .bam wasn't even created correctly and that likely causes the downstream errors. Since you have not given a RAM limit, there will be several instances of STAR that will attempt to run in parallel. Catching errors and automatically aborting downstream processes is something that zUMIs lacks, so it's good to read the log carefully. I personally haven't seen the "tmp.fifo.header: Directory nonexistent" error message & will try to reproduce that on my side.
- Related: I'd recommend also setting an explicit memory limit, just to be sure the resources of the machine don't get exhausted. E.g. `mem_limit: 50` (the units are Gb)
- In the log, you mention that certain steps took several hours - that was then for the full dataset, not the 1 mio dataset? Otherwise something else might be up.

Since I know from users that reanalysed the ArrayExpress data or generated their own Smart-seq3 data, we should get this to work. Which zUMIs version are you using here?

To confirm that the current version in GitHub does what it should and is not dependent on something installed in my system, I create a fresh AWS EC2 instance (Amazon Linux 2 AMI) and installed current zUMIs:
```
sudo yum install git
git clone https://github.com/sdparekh/zUMIs.git
```

This is the yaml I used with a 1 mio read dataset from the Mouse Fibroblasts in ArrayExpress & a chr19 genome index (for faster copying of reference):
```
project: Fibro_test
sequence_files:
  file1:
    name: /home/ec2-user/fibro_testdata/Smartseq3.Fibroblasts.NovaSeq.read1.1mio.fastq.gz
    base_definition:
      - cDNA(23-150)
      - UMI(12-19)
    find_pattern: ATTGCGCAATG
  file2:
    name: /home/ec2-user/fibro_testdata/Smartseq3.Fibroblasts.NovaSeq.read2.1mio.fastq.gz
    base_definition:
      - cDNA(1-150)
  file3:
    name: /home/ec2-user/fibro_testdata/Smartseq3.Fibroblasts.NovaSeq.index1.1mio.fastq.gz
    base_definition: BC(1-8)
  file4:
    name: /home/ec2-user/fibro_testdata/Smartseq3.Fibroblasts.NovaSeq.index2.1mio.fastq.gz
    base_definition: BC(1-8)
reference:
  STAR_index: /home/ec2-user/mouse_chr19/chr19_STAR7_idx
  GTF_file: /home/ec2-user/mouse_chr19/Mus_musculus.GRCm38.91.chr19.gtf
  exon_extension: no
  extension_length: 0
  scaffold_length_min: 0
  additional_files: ~
  additional_STAR_params: '--clip3pAdapterSeq CTGTCTCTTATACACATCT'
out_dir: /home/ec2-user/out
num_threads: 8
mem_limit: 30
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  barcode_sharing: ~
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: no
counting_opts:
  introns: yes
  intronProb: no
  downsampling: 0
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  multi_overlap: no
  twoPass: no
make_stats: yes
which_Stage: Filtering
```

Output verbose:
```
./zUMIs/zUMIs.sh -c -y Smart3_Fibro.yaml
Using miniconda environment for zUMIs!
 note: internal executables will be used instead of those specified in the YAML file!


 You provided these parameters:
 YAML file:	Smart3_Fibro.yaml
 zUMIs directory:		/home/ec2-user/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   30
 zUMIs version 2.9.3


fre jul 17 07:03:12 UTC 2020
WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.1a. This may
 lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR
 index using STAR 2.7.3a.
Filtering...
fre jul 17 07:03:46 UTC 2020
[1] "12 barcodes detected."
[1] "6222 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Found 17 daughter barcodes that can be binned into 1 parent barcodes."
[1] "Binned barcodes correspond to 5195 reads."
Mapping...
[1] "2020-07-17 07:03:53 UTC"
Warning message:
NAs introduced by coercion
Jul 17 07:03:53 ..... started STAR run
Jul 17 07:03:53 ..... loading genome
Jul 17 07:03:54 ..... processing annotations GTF
Jul 17 07:03:54 ..... inserting junctions into the genome indices
Jul 17 07:04:09 ..... started mapping
Jul 17 08:37:21 ..... finished mapping
Jul 17 08:37:21 ..... finished successfully
fre jul 17 08:37:22 UTC 2020
Counting...
[1] "9e+07 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/ec2-user/out/Fibro_test.final_annot.gtf"
[1] "Annotation loaded!"
Warning message:
`as_quosure()` requires an explicit environment as of rlang 0.3.0.
Please supply `env`.
This warning is displayed once per session.
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           P Fibro_test.filtered.tagged.Aligned.out.bam     ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid13049 ...         ||
||    Features : 8040                                                         ||
||    Meta-features : 1098                                                    ||
||    Chromosomes/contigs : 1                                                 ||
||                                                                            ||
|| Process BAM file Fibro_test.filtered.tagged.Aligned.out.bam...             ||
||    Paired-end reads are included.                                          ||
||    Assign alignments (paired-end) to features...                           ||
||    Total alignments : 892920                                               ||
||    Successfully assigned alignments : 46462 (5.2%)                         ||
||    Running time : 0.04 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           P Fibro_test.filtered.tagged.Aligned.out.bam ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid13049 ...         ||
||    Features : 6631                                                         ||
||    Meta-features : 733                                                     ||
||    Chromosomes/contigs : 1                                                 ||
||                                                                            ||
|| Process BAM file Fibro_test.filtered.tagged.Aligned.out.bam.ex.feature ... ||
||    Paired-end reads are included.                                          ||
||    Assign alignments (paired-end) to features...                           ||
||    Total alignments : 892920                                               ||
||    Successfully assigned alignments : 30305 (3.4%)                         ||
||    Running time : 0.04 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "2020-07-17 08:43:04 UTC"
[1] "Coordinate sorting final bam file..."
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
[1] "2020-07-17 08:43:07 UTC"
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 12 barcodes in this chunk..."
[1] "2020-07-17 08:43:17 UTC"
[1] "I am done!! Look what I produced.../home/ec2-user/out/zUMIs_output/"
           used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells  7339673 392.0   12293147 656.6 12293147 656.6
Vcells 13215705 100.9   42505520 324.3 42495864 324.3
fre jul 17 08:43:18 UTC 2020
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%fre jul 17 08:43:25 UTC 2020
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-07-17 08:43:26 UTC"
[1] "Counting UMI fragments..."
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.
[1] "9e+07 Reads per chunk"
[1] "Extracting reads from bam file(s)..."
[1] "Working on chunk 1"
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4423583 236.3    8421164 449.8  8385551 447.9
Vcells 7948852  60.7   23529300 179.6 23164915 176.8
fre jul 17 08:43:44 UTC 2020
```

This confirms to me that the pipeline is working as I expect!
To move forward, I recommend you clone the current version and start over in a new output directory (zUMIs should overwrite in place, but maybe good to avoid issues with permissions, etc.). 
I do recommend setting the -c (conda) flag (ie. zUMIs.sh -c -y xyz.yaml) so that the dependencies all play well. 

That being said, I don't see any obvious problems in your YAML file, but I included mine above for comparison.

Best,

Christoph

**Comment by gringer** [comment]
Memory limit on my computer is about 500 GB, although it goes into a SSD swap file (still reasonably fast) if above 64 GB. I might as well set the limit to 50 GB if the parallelisation is likely to slow it down. If zUMIs is writing a lot to disk, that'd also cause problems due to the file system setup (in which case I'd need to store output locally).

This was with 2.9.3, but I'll do a fresh clone and see if it improves things.

**Comment by cziegenhain** [comment]
Oh yes, it's definitely preferable to stay within the limits of the actual RAM! In my experience SSD swap does still slow things down.
There are quite some read-write steps, eg. for sorting of bam files using samtools.

2.9.3 sounds up to date, but hopefully things will go better now.

**Comment by sanxiongliu** [comment]
Hi,

I also tried to reproduce the scRNA-Seq data from the papaer using zUMIs. I always got the same error: Error in data.table::fread(paste(samtools, "view", filtered_bams[1], "| cut -f10 | head -n 1000"),  : 
  input= contains no \n or \r, but starts with a space. Please remove the leading space, or use text=, file= or cmd=
Execution halted.

It seems an error in the intermediate file. Can you suggest a solution? Thanks.

[Liu_9456325.txt](https://github.com/sdparekh/zUMIs/files/5204698/Liu_9456325.txt)
[run.yaml.txt](https://github.com/sdparekh/zUMIs/files/5204699/run.yaml.txt)

**Comment by cziegenhain** [comment]
Feel free to reopen if you need additional help.

**Comment by HaniJieunKim** [comment]
Hi Christoph! 

Thank you for maintaining such a great tool!

Just adding onto this thread to ask whether you could provide the corresponding yaml script if we were to produce a reads data rather than count data (thus ignoring UMIs) using zUMI? 

Thank you for your time.

Best regards,

Hani

**Comment by cziegenhain** [comment]
Hi Hani,

With zUMIs you also always additionally receive quantification in read counts without UMIs. You do not need a separate yaml or run.

Best,
C

**Comment by HaniJieunKim** [comment]
Dear Christoph,

Thank you for the swift response! Apologies for commenting on a closed thread, but I thought it would be relevant to post here as I am also trying to reproduce the Fibroblast data from the Smart-seq3 paper (also downloaded from ArrayExpress.

I have tried to go through the past issues to troubleshoot and have successfully run the example data. But I haven't had any luck so far to successfully run zUMI on this data.

I would be much grateful for any advice on what may be the issue.

Many thanks for your time in advance. 

Best regards,

Hani

```
project: Fibro_test
sequence_files:
  file1:
    name: /home/data/Smart-seq3/raw/Smartseq3.Fibroblasts.NovaSeq.R1.fastq.gz
    base_definition:
    - cDNA(23-150)
    - UMI(12-19)
    find_pattern: ATTGCGCAATG
  file2:
    name: /home/data/Smart-seq3/raw/Smartseq3.Fibroblasts.NovaSeq.R2.fastq.gz
    base_definition:
    - cDNA(1-150)
  file3:
    name: /home/data/Smart-seq3/raw/Smartseq3.Fibroblasts.NovaSeq.I1.fastq.gz
    base_definition:
    - BC(1-8)
  file4:
    name: /home/data/Smart-seq3/raw/Smartseq3.Fibroblasts.NovaSeq.I2.fastq.gz
    base_definition:
    - BC(1-8)
reference:
  STAR_index: /home/data/genomeDir/STARgenomes/mouse2
  GTF_file: /home/data/genomeDir/refdata-gex-mm10-2020-A/genes/genes.gtf
  exon_extension: no
  extension_length: 0
  scaffold_length_min: 0
  additional_STAR_params: '--clip3pAdapterSeq CTGTCTCTTATACACATCT'
  additional_files: ~
out_dir: /home/data/normalisation/zUMI/test2
num_threads: 30
mem_limit: 200
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  barcode_sharing: ~
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
counting_opts:
  introns: yes
  intronProb: no
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  multi_overlap: no
  twoPass: no
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
#STAR_exec: '/home/ubuntu/STAR/bin/Linux_x86_64/STAR'
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
```

```
$file1
NULL

$file2
NULL

$file3
NULL

$file4
NULL

[1] ""
[1] ""
[1] ""
[1] ""
[1] "" "" "" ""
[1] ""
[1] ""
[1] ""
[1] ""
[1] "" "" "" ""
[1] "NULL" "NULL" "NULL" "NULL"
$file1
NULL

$file2
NULL

$file3
NULL

$file4
NULL

$file1
NULL

$file2
NULL

$file3
NULL

$file4
NULL

[1] 0
```
