### ISSUE TITLE
STAR threads issue

### ISSUE THREAD

**Issue by fmriemers** [sdparekh/zUMIs#201]
Thank you for developing zUMIS. Have an issue that might not pop up unless you run with less memory than the genome size or with less than 25 GB of memory if the genome-size detection fails and the default genome size of 25 is assigned.
Testing the latest ( 2.9.3c) version of zUMIs with the small HEK data set you provide. Made the STAR index, without GTF, for human chromosome 22 with STAR 2.7.1a. Running this generates an error during the mapping stage as STAR gets set to Inf threads as shown in the console_output_01 below. Furthermore, in the STAR command line in the log file local_test02_star271.filtered.tagged.Log.out. the --runThreadN Inf can be seen.
As the problem clearly occurred at the mapping stage had a look into the _zUMIS-mapping.R_ code and found that the code used to set the number of available threads for STAR is dependent on the number of instances of STAR. The calculation of the number of instances of STAR from the number of available cores set by the user in the YAML file divided by the genome size (`num_star_instances <- floor(inp$mem_limit/genome_size)`) can result in 0. Which in turn gives the calculation of the available cores from the division of available cores by the number of STAR instances a division by zero (`avail_cores <- floor(avail_cores / num_star_instances)`) and an Inf as a result.
The code to set the available cores to 1 when lower than 2  (`if(avail_cores < 2){  avail_cores = 1}`) will not work on an Inf value thus will stay an Inf and thus the cores in the STAR call gets the Inf value.
After changing the code to prevent the number of star instances from being 0 the rest of the pipeline runs as it should.

Regards Frank

```
******** console_output_01 ********

zUMIs-main/zUMIs.sh -y /opt/zumis/zUMIs/zUMIs_test02.yaml 
You provided these parameters:
YAML file:	/opt/zumis/zUMIs/zUMIs_test02.yaml
zUMIs directory:		/opt/zumis/zUMIs-main
STAR executable		STAR271
samtools executable		samtools
pigz executable		pigz
Rscript executable		Rscript
RAM limit:   16
zUMIs version 2.9.3c 


di 21 jul 2020 15:16:44 CEST
Filtering...
di 21 jul 2020 15:17:16 CEST
[1] "43 barcodes detected."
[1] "193783 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Found 2 daughter barcodes that can be binned into 2 parent barcodes."
[1] "Binned barcodes correspond to 242 reads."
Mapping...
[1] "2020-07-21 15:17:23 CEST"
Warning message:
NAs introduced by coercion 

EXITING: fatal input ERROR: runThreadN must be >0, user-defined runThreadN=0

Jul 21 15:17:23 ...... FATAL ERROR, exiting
```

```
***************** local_test02_star271.filtered.tagged.Log.out ***************

##### Command Line:
STAR271 --readFilesCommand samtools view -@ 1 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /opt/zumis/testdata/chr22/hg38_99_chr22_nogtf_star271 --sjdbGTFfile /opt/zumis/testdata/reference/GRCh38.99.chr22.gtf --runThreadN Inf --sjdbOverhang 49 --readFilesType SAM SE --twopassMode Basic --readFilesIn /opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271aa.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ab.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ac.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ad.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ae.filtered.tagged.bam --outFileNamePrefix /opt/zumis/testresult_main/local_test02_star271.filtered.tagged.
##### Initial USER parameters from Command Line:
outFileNamePrefix                 /opt/zumis/testresult_main/local_test02_star271.filtered.tagged.
###### All USER parameters from Command Line:
readFilesCommand              samtools   view   -@   1        ~RE-DEFINED
outSAMmultNmax                1     ~RE-DEFINED
outFilterMultimapNmax         50     ~RE-DEFINED
outSAMunmapped                Within        ~RE-DEFINED
outSAMtype                    BAM   Unsorted        ~RE-DEFINED
quantMode                     TranscriptomeSAM        ~RE-DEFINED
genomeDir                     /opt/zumis/testdata/chr22/hg38_99_chr22_nogtf_star271     ~RE-DEFINED
sjdbGTFfile                   /opt/zumis/testdata/reference/GRCh38.99.chr22.gtf     ~RE-DEFINED
runThreadN                    0     ~RE-DEFINED
sjdbOverhang                  49     ~RE-DEFINED
readFilesType                 SAM   SE        ~RE-DEFINED
twopassMode                   Basic     ~RE-DEFINED
readFilesIn                   /opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271aa.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ab.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ac.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ad.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ae.filtered.tagged.bam        ~RE-DEFINED
outFileNamePrefix             /opt/zumis/testresult_main/local_test02_star271.filtered.tagged.     ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runThreadN                        0
genomeDir                         /opt/zumis/testdata/chr22/hg38_99_chr22_nogtf_star271
readFilesType                     SAM   SE   
readFilesIn                       /opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271aa.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ab.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ac.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ad.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ae.filtered.tagged.bam   
readFilesCommand                  samtools   view   -@   1   
outFileNamePrefix                 /opt/zumis/testresult_main/local_test02_star271.filtered.tagged.
outSAMtype                        BAM   Unsorted   
outSAMunmapped                    Within   
outSAMmultNmax                    1
outFilterMultimapNmax             50
sjdbGTFfile                       /opt/zumis/testdata/reference/GRCh38.99.chr22.gtf
sjdbOverhang                      49
quantMode                         TranscriptomeSAM   
twopassMode                       Basic

-------------------------------
##### Final effective command line:
STAR271   --runThreadN 0   --genomeDir /opt/zumis/testdata/chr22/hg38_99_chr22_nogtf_star271   --readFilesType SAM   SE      --readFilesIn /opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271aa.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ab.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ac.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ad.filtered.tagged.bam,/opt/zumis/testresult_main/zUMIs_output/.tmpMerge//local_test02_star271.local_test02_star271ae.filtered.tagged.bam      --readFilesCommand samtools   view   -@   1      --outFileNamePrefix /opt/zumis/testresult_main/local_test02_star271.filtered.tagged.   --outSAMtype BAM   Unsorted      --outSAMunmapped Within      --outSAMmultNmax 1   --outFilterMultimapNmax 50   --sjdbGTFfile /opt/zumis/testdata/reference/GRCh38.99.chr22.gtf   --sjdbOverhang 49   --quantMode TranscriptomeSAM      --twopassMode Basic

##### Final parameters after user input--------------------------------:
versionGenome                     2.7.1a
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        0
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         /opt/zumis/testdata/chr22/hg38_99_chr22_nogtf_star271
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     SAM   SE 
```

```
*** /opt/zumis/zUMIs/zUMIs_test02.yaml ***
###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project: local_test02_star271

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /opt/zumis/testdata/barcoderead_HEK.1mio.fq.gz
    base_definition:
      - BC(1-6) #example:BC(1-6)
      - UMI(7-16) #example:UMI(7-16)
  file2:
    name:  /opt/zumis/testdata/cDNAread_HEK.1mio.fq.gz #path to second file
    base_definition:
      - cDNA(1-50) #example:cDNA(1-50)


#reference genome setup
reference:
  STAR_index: /opt/zumis/testdata/chr22/hg38_99_chr22_nogtf_star271
  GTF_file: /opt/zumis/testdata/reference/GRCh38.99.chr22.gtf #path to gene annotation file in GTF format
  exon_extension: no #extend exons by a certain width?
  extension_length: 0 #number of bp to extend exons by
  scaffold_length_min: 0 #minimal scaffold/chromosome length to consider (0 = all)
  additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params: #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: /opt/zumis/testresult_main #specify the full path to the output directory

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 3
mem_limit: 16 #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  barcode_sharing: null #Optional for combining several barcode sequences per cell (see github wiki)
  automatic: yes #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 100 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  intronProb: no #perform an estimation of how likely intronic reads are to be derived from mRNA by comparing to intergenic counts.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  #write_ham: no #If hamming distance collapse of UMI sequences is performed, write out mapping tables & UB corrected bam files.
  velocyto: no #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  multi_overlap: no #Do you want to assign reads overlapping to multiple features?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes


#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths
samtools_exec: samtools #samtools executable
Rscript_exec: Rscript #Rscript executable
STAR_exec: STAR271 #STAR executable
pigz_exec: pigz #pigz executable

#below, fqfilter will add a read_layout flag defining SE or PE
zUMIs_directory: /opt/zumis/zUMIs-main
read_layout: SE
```
