### ISSUE TITLE
EXITING: fatal input ERROR: runThreadN must be >0, user-defined runThreadN=0

### ISSUE THREAD

**Issue by doctorasgr** [sdparekh/zUMIs#207]
**Describe the bug**
I was trying to run zUMIs yesterday after generating a genome index for a scRNA-seq. Filtering stage was alright but after that I got the message:
`EXITING: fatal input ERROR: runThreadN must be >0, user-defined runThreadN=0
`
It is quite odd as I chose 3 as the number of threads.
This is my yaml file
```
project: Severe1
sequence_files:
  file1:
    name: /media/doctoras/Elements/Project/BAL/Severe/SRR11537950_C149_R1.fastq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: /media/doctoras/Elements/Project/BAL/Severe/SRR11537950_C149_R2.fastq.gz
    base_definition:
    - cDNA(1-50)
reference:
  STAR_index: /media/doctoras/Elements/Bioinformatics/Indexes/STAR/New
  GTF_file: /media/doctoras/Elements/Bioinformatics/Indexes/ENSEMBL/Homo_sapiens.GRCh38.100.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /media/doctoras/Elements/Project/BAL/Severe/1
num_threads: 3
mem_limit: 10
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  barcode_sharing: ''
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: no
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  write_ham: no
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: /home/doctoras/Bioinformatics/Tools/STAR-2.7.3a/source/STAR
pigz_exec: pigz
samtools_exec: samtools
```
Here is the complete output I had after running this yaml:
```
(base) doctoras@buddy:/media/doctoras/Elements/Project/BAL/Severe/1$ zUMIs.sh -y Severe1.yaml
------------- 

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs 

-------------


 You provided these parameters:
 YAML file:	Severe1.yaml
 zUMIs directory:		/home/doctoras/Bioinformatics/Tools/zUMIs-main
 STAR executable		/home/doctoras/Bioinformatics/Tools/STAR-2.7.3a/source/STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   10
 zUMIs version 2.9.0 


Tue 18 Aug 23:31:44 BST 2020
**WARNING**: The STAR version used for mapping is **2.7.3a** and the STAR index was created using the version **2.7.1a**. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR **2.7.3a**.
Filtering...
Use of uninitialized value $lay in string eq at /home/doctoras/Bioinformatics/Tools/zUMIs-main/fqfilter_v2.pl line 312, <$fhTmp> line 4.
Use of uninitialized value $lay in string eq at /home/doctoras/Bioinformatics/Tools/zUMIs-main/fqfilter_v2.pl line 312, <$fhTmp> line 4.
Wed 19 Aug 10:10:34 BST 2020
[1] "481 barcodes detected."
[1] "14351590 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Found 895 daughter barcodes that can be binned into 391 parent barcodes."
[1] "Binned barcodes correspond to 2798036 reads."
Mapping...
[1] "2020-08-19 12:04:38 BST"

**EXITING: fatal input ERROR: runThreadN must be >0, user-defined runThreadN=0**

Aug 19 12:05:03 ...... FATAL ERROR, exiting
Wed 19 Aug 12:22:39 BST 2020
Counting...
[1] "2020-08-19 12:22:53 BST"
[1] "4.5e+07 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/media/doctoras/Elements/Project/BAL/Severe/1/Severe1.final_annot.gtf"
[main_samview] fail to read the header from "/media/doctoras/Elements/Project/BAL/Severe/1/Severe1.filtered.tagged.Aligned.out.bam".
[main_samview] fail to read the header from "/media/doctoras/Elements/Project/BAL/Severe/1/Severe1.filtered.tagged.Aligned.out.bam".
Error in gsub("SN:", "", chr) : object 'chr' not found
Calls: .makeSAF ... .chromLengthFilter -> [ -> [.data.table -> eval -> eval -> gsub
In addition: Warning message:
In data.table::fread(bread, col.names = c("chr", "len"), header = F) :
  File '/tmp/RtmpIXt9yk/file26da07c09a2db' has size 0. Returning a NULL data.table.
Execution halted
Wed 19 Aug 12:23:35 BST 2020
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/media/doctoras/Elements/Project/BAL/Severe/1/zUMIs_output/expression/Severe1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Wed 19 Aug 12:23:39 BST 2020
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-08-19 12:23:39 BST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/media/doctoras/Elements/Project/BAL/Severe/1/zUMIs_output/expression/Severe1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Wed 19 Aug 12:23:43 BST 2020

```

 - OS: Ubuntu 
 - Version 20.04.1 LTS

The other weird thing is that although I used STAR 2.7.3a to generate the genome index zUMIs thinks that I used STAR 2.7.1a

Thank you in advance for your kind response.
