### ISSUE TITLE
'output_UMI/UMI.final_annot.gtf' does not exist

### ISSUE THREAD

**Issue by cpattaroni** [sdparekh/zUMIs#247]
Hi zUMIs team,

Thanks a lot for this amazing tool! I've been stuck after the mapping step. Filtering seems to works fine, alignment as well. 

It seems like `kept_barcodes_binned.txt` is not produced.

Here is the YAML file:
```
###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project: UMI

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /fs03/of33/Celine/QiagenzUMIs/data/QiagenUPXTranscriptome96samples_S1_L001_R2_001.fastq.gz #path to first file
    base_definition:
      - BC(1-35)
      - UMI(36-47)
  file2:
    name: /fs03/of33/Celine/QiagenzUMIs/data/QiagenUPXTranscriptome96samples_S1_L001_R1_001.fastq.gz #path to second file
    base_definition:
      - cDNA(1-87)
#reference genome setup
reference:
  STAR_index: /fs03/of33/Celine/QiagenzUMIs/db #path to STAR genome index
  GTF_file: /fs03/of33/Celine/QiagenzUMIs/db/Mus_musculus.GRCm38.98.gtf #path to gene annotation file in GTF format
  exon_extension: no #extend exons by a certain width?
  extension_length: 0 #number of bp to extend exons by
  scaffold_length_min: 0 #minimal scaffold/chromosome length to consider (0 = all)
  additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params: #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: output_UMI #specify the full path to the output directory

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 18
mem_limit: null #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  barcode_sharing: null #Optional for combining several barcode sequences per cell (see github wiki)
  automatic: yes #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 100 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  intronProb: no #perform an estimation of how likely intronic reads are to be derived from mRNA by comparing to intergenic counts.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  velocyto: no #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  multi_overlap: no #Do you want to assign reads overlapping to multiple features?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes

#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths
samtools_exec: samtools #samtools executable
Rscript_exec: Rscript #Rscript executable
STAR_exec: STAR #STAR executable
pigz_exec: pigz #pigz executable

#below, fqfilter will add a read_layout flag defining SE or PE
```

Here is the full output:

```
Feb 23 14:50:30 ..... inserting junctions into the genome indices
Feb 23 14:51:53 ..... started mapping
Feb 23 14:56:32 ..... finished 1st pass mapping
Feb 23 14:56:32 ..... inserting junctions into the genome indices
Feb 23 14:57:58 ..... started mapping
Feb 23 15:08:23 ..... finished mapping
Feb 23 15:08:23 ..... finished successfully
Feb 23 15:19:16 ..... finished mapping
Feb 23 15:19:17 ..... finished successfully
Tue Feb 23 15:20:17 AEDT 2021
Counting...
[1] "2021-02-23 15:20:50 AEDT"
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes_binned.txt")) : 
  File 'output_UMI/zUMIs_output/UMIkept_barcodes_binned.txt' does not exist or is non-readable. getwd()=='/fs03/of33/Celine/QiagenzUMIs/output_UMI'
Execution halted
```

Here are the files that were created:
```
total 49G
-rw-r--r-- 1 cpat0003 of33  14M Feb 23 14:21 UMI.BCstats.txt
-rw-r--r-- 1 cpat0003 of33  20G Feb 23 15:20 UMI.filtered.tagged.Aligned.out.bam
-rw-r--r-- 1 cpat0003 of33  16G Feb 23 15:20 UMI.filtered.tagged.Aligned.toTranscriptome.out.bam
-rw-r--r-- 1 cpat0003 of33 6.0K Feb 23 15:19 UMI.filtered.tagged.Log.final.out
-rw-r--r-- 1 cpat0003 of33  13G Feb 23 14:22 UMI.filtered.tagged.unmapped.bam
-rw-r--r-- 1 cpat0003 of33 769M Feb 23 14:22 UMI.final_annot.gtf
-rw-r--r-- 1 cpat0003 of33  266 Feb 23 11:36 UMI.zUMIs_runlog.txt
drwxr-sr-x 6 cpat0003 of33 4.0K Feb 23 14:22 zUMIs_output
```

Working on a cluster, 300Gb memory and 20 threads. I am using the Qiagen UPX transcriptome kit which has a cell barcode (35bp) and UMI (12bp) on R2, R1 is the actual transcript. 

Thanks so much in advance for your help.
