### ISSUE TITLE
Analysis of the results generated by zUMIs 

### ISSUE THREAD

**Issue by HealHer** [sdparekh/zUMIs#258]
Hello, 

Thank you very much for _zUMIs_. The program is very stable and allows many things. I use zUMIs to align private data in order to get processing leads. 

### Running zUMIs on private datasets
We tried to run zUMIs on 2 datasets (p1 and p2), coming from 2 very close human patients with the same initial condition. Both run used 10x Chromium v2 sequencing protocol. The program runs (the .yaml files are available at the end of the issue). We use custom STAR indexes and a human _**Hg38**_ genome. The indexes are generated using: 
```
STAR  --runMode genomeGenerate  
--runThreadN 12   
--genomeDir indexFolder 
--genomeFastaFiles genome.fa 
--genomeSAindexNbases 14 
--genomeChrBinNbits 18 
--genomeSAsparseD 3 
--limitGenomeGenerateRAM 17179869184 
--sjdbGTFfile genes.gtf
```

### Error sometimes occuring
There is sometimes an error occuring on the `Counting` phase. Re-running the by changing the `which_Stage` option to `Counting` solve the issue. The error is always the same: 
```
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 2"
[1] "Processing 3122 barcodes in this chunk..."
[1] "Working on barcode chunk 2 out of 2"
[1] "Processing 3435 barcodes in this chunk..."
Error in alldt[[i]][[2]] : subscript out of bounds
Calls: bindList
In addition: Warning message:
In parallel::mclapply(mapList, function(tt) { :
  scheduled core 2 did not deliver a result, all values of the job will be affected
Execution halted
```

### Compute output
The `.rds` files of the runs _p1_ and _p2_ are converted into _anndata_ (_.h5df_ and then _.h5ad_) by using the `DropletUtils.write10xcounts()` module.
```
rds_object <- readRDS(file)
dgecounts_exon <- rds_object$umicount$exon$all
write10xCounts('./exon_output.h5df', dgecounts_exon, overwrite=TRUE)
```

When we analyze the results by linear regression we obtain a horizontal orthogonal line proving that the genes aligned in run 1 are all different from run 2 ([figure here](https://user-images.githubusercontent.com/52368220/117314849-7283f280-ae87-11eb-9837-c1ae3b39ee82.png))

We try reproducing these runs using cellranger in the same enviroment using custom indexes generated by the same method. After QC we detect many identical parameters (like _number of cells_, _number of reads_ or _distribution_), but however a linear regression places the two runs (p1 and p2) with the same proportions following almost gene(p1) = gene(p2) ([figure here](https://user-images.githubusercontent.com/52368220/117315353-e920f000-ae87-11eb-8bdf-4937403a3a43.png)) 

In light of the `.run.yaml` files that allowed us to run the alignment and treatement, would it be possible for you to see if I'm forgetting any important options that could cause this? 

Let me know if you need more information, 

Thank you very much for your time 

Alexis

### Ressources
_p1.run.yaml_ 
```
Rscript_exec: Rscript
STAR_exec: STAR
barcodes:
  BarcodeBinning: 1
  automatic: true
  barcode_file: null
  barcode_num: null
  barcode_sharing: null
  demultiplex: false
  nReadsperCell: 100
counting_opts:
  Ham_Dist: 0
  downsampling: 0
  intronProb: false
  introns: true
  multi_overlap: false
  primaryHit: true
  strand: 0
  twoPass: true
  velocyto: false
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
make_stats: true
mem_limit: 65
num_threads: 12
out_dir: /mnt/vol-extra/workspace/alignment
pigz_exec: pigz
project: p1
reference:
  GTF_file: /mnt/vol_extra/workspace/reference_genome/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf
  STAR_index: /mnt/vol-extra/workspace/reference_genome/STAR_index
  additional_STAR_params: --limitSjdbInsertNsj 1022629
  additional_files: null
  exon_extension: false
  extension_length: 0
  scaffold_length_min: 0
samtools_exec: samtools
sequence_files:
  file1:
    base_definition:
    - BC(1-16)
    - UMI(17-26)
    name: /mnt/vol-extra/scRNA_data/CD28_P1/CD28_P1_S1_L001_R1_001.fastq.gz
  file2:
    base_definition:
    - cDNA(1-101)
    name: /mnt/vol-extra/scRNA_data/CD28_P1/CD28_P1_S1_L001_R2_001.fastq.gz
  file3:
    base_definition:
    - UMI(1-8)
    name: /mnt/vol-extra/scRNA_data/CD28_P1/CD28_P1_S1_L001_I1_001.fastq.gz
which_Stage: Filtering
zUMIs_directory: ./zUMIs
read_layout: SE
```
_p2.run.yaml_
```
Rscript_exec: Rscript
STAR_exec: STAR
barcodes:
  BarcodeBinning: 1
  automatic: true
  barcode_file: null
  barcode_num: null
  barcode_sharing: null
  demultiplex: false
  nReadsperCell: 100
counting_opts:
  Ham_Dist: 0
  downsampling: 0
  intronProb: false
  introns: true
  multi_overlap: false
  primaryHit: true
  strand: 0
  twoPass: true
  velocyto: false
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
make_stats: true
mem_limit: 65
num_threads: 12
out_dir: /mnt/vol-extra/workspace/alignment
pigz_exec: pigz
project: p2
reference:
  GTF_file: /mnt/vol_extra/workspace/reference_genome/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf
  STAR_index: /mnt/vol-extra/workspace/reference_genome/STAR_index
  additional_STAR_params: --limitSjdbInsertNsj 1022629
  additional_files: null
  exon_extension: false
  extension_length: 0
  scaffold_length_min: 0
samtools_exec: samtools
sequence_files:
  file1:
    base_definition:
    - BC(1-16)
    - UMI(17-26)
    name: /mnt/vol-extra/scRNA_data/CD28_P2/CD28_P2_S1_L001_R1_001.fastq.gz
  file2:
    base_definition:
    - cDNA(1-101)
    name: /mnt/vol-extra/scRNA_data/CD28_P2/CD28_P2_S1_L001_R2_001.fastq.gz
  file3:
    base_definition:
    - UMI(1-8)
    name: /mnt/vol-extra/scRNA_data/CD28_P2/CD28_P2_S1_L001_I1_001.fastq.gz
which_Stage: Filtering
zUMIs_directory: ./zUMIs
read_layout: SE
```
