### ISSUE TITLE
samtools in miniconda looks problematic 

### ISSUE THREAD

**Issue by roxyisat-rex** [sdparekh/zUMIs#287]
Hi Christoph 

I am writing in hopes of reopening issue [#283](https://github.com/sdparekh/zUMIs/issues/283) (Sorry about the delay in getting back, I was working on another project which was quite urgent). 
I re-ran with the test/ sample data provided in the [usage link](https://github.com/sdparekh/zUMIs/wiki/Usage). 
Below is the error from terminal: 
```
Loading anaconda3/personal
  Loading requirement: fix_unwritable_tmp fix_setxattr
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
Error in uik(bccount$cellindex, bccount$cs/1000) : 
  Method is not applicable for such a small vector. Please give at least a 5 numbers vector
Calls: cellBC -> .cellBarcode_unknown -> .FindBCcut -> uik
Execution halted
Warning message:
NAs introduced by coercion 
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) : 
  File '/rds/general/user/xyz16/home/bob/zUMIs_output/SS3_human_2samples_testkept_barcodes.txt' does not exist or is non-readable. getwd()=='/rds/general/user/xyz16/home/bob'
Execution halted
Loading required package: yaml
Loading required package: Matrix
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/rds/general/user/xyz16/home/bob/zUMIs_output/expression/SS3_human_2samples_test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  : 
  File '/rds/general/user/xyz16/home/bob/zUMIs_output/SS3_human_2samples_testkept_barcodes.txt' does not exist or is non-readable. getwd()=='/rds/general/user/xyz16/home/bob'
Execution halted
```
This is quite similar to the issue above (when I was using my own Smartseq 3 data described in the previous issue) including 
1. the absence of the `project.dgecounts.rds` files. 
2. samtools view: writing to standard output failed: Broken pipe 
3. error in fread 
I think this error may originate from something to do with the samtools in the miniconda env.

The other part of the terminal output shows the below 
Also similar to when I was using my own data. Pausing at descriptive statistics.
```
 You provided these parameters:
 YAML file:	runExample_fix.yaml
 zUMIs directory:		/rds/general/user/xyz16/home/bob/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   20
 zUMIs version 2.9.7 

Thu 28 Oct 07:51:18 BST 2021
WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.1a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.3a.
Filtering...
Thu 28 Oct 07:51:30 BST 2021
Mapping...
[1] "2021-10-28 07:51:33 BST"
Oct 28 07:51:33 ..... started STAR run
Oct 28 07:51:34 ..... loading genome
Oct 28 07:51:34 ..... processing annotations GTF
Oct 28 07:51:35 ..... inserting junctions into the genome indices
Oct 28 07:51:38 ..... started 1st pass mapping
Oct 28 07:53:39 ..... finished 1st pass mapping
Oct 28 07:53:39 ..... inserting junctions into the genome indices
Oct 28 07:53:43 ..... started mapping
Oct 28 07:55:48 ..... finished mapping
Oct 28 07:55:48 ..... finished successfully
Thu 28 Oct 07:55:48 BST 2021
Counting...
[1] "2021-10-28 07:56:16 BST"
Thu 28 Oct 07:56:16 BST 2021
[1] "loomR found"
Thu 28 Oct 07:56:19 BST 2021
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2021-10-28 07:56:19 BST"
Thu 28 Oct 07:56:30 BST 2021
```

To answer your question previous:
When I was using my own ss3 data, I did not get the *.filtered.tagged.unmapped.bam file in the output directory. I got the following output files:

project.BCstats.txt (1.38 MB)
project.filtered.tagged.Log.final.out (0KB)
project.final_annot.gtf (1.2GB)
project.zUMIs_runlog.txt (1KB)
project.barcodes.txt (5KB)
output directories include expression and stats, however both empty.
when using the test data describe above, I got:

filtered.tagged.Aligned.out.bam (63.9MB)
filtered.Aligned.toTranscriptome.out.bam (47MB)
filtered.tagged.of.final.out (2kb)
figered.tagged.log.out (22kb)
fitered.tagged.log.progress.out (1kb)
filtered.tagged.SJ.out.tab (263kb)
t.filtered.tagged.unmapped.bam (50mb)
.final_annot.gtf(24mb)
.BC.stats.txt (1kb)

Here is my YAML for the sample data:
```
project: SS3_human_2samples_test
sequence_files:
  file1:
    name: /rds/general/user/xyz16/home/bob/barcoderead_HEK.1mio.fq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: /rds/general/user/xyz16/home/bob/cDNAread_HEK.1mio.fq.gz
    base_definition: 
    - cDNA(1-50)
reference:
  STAR_index: /rds/general/user/xyz16/home/bob/hg38_chr22_STAR7
  GTF_file: /rds/general/user/xyz16/home/bob/GRCh38.95.chr22.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /rds/general/user/xyz16/home/bob
num_threads: 8
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools 
zUMIs_directory: /rds/general/user/xyz16/home/bob/zUMIs
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
read_layout: PE
```
Your help and advice is much appreciated.  Thank you very much!

_Originally posted by @roxyisat-rex in https://github.com/sdparekh/zUMIs/issues/283#issuecomment-953735987_
