### ISSUE TITLE
zUMIs.YAML.error.log: All files "NULL"

### ISSUE THREAD

**Issue by carmensandoval** [sdparekh/zUMIs#330]
Hi,

I can't figure out what I'm doing wrong in setting up zUMIs. This is what my YAML looks like:

```
project: bulk_smartseq_umis
sequence_files:
  file1:
    name: /path/to/bulk_RNA/bcl2fastq/fastqs/Undetermined_S0_R1_001.fastq.gz
    base_definition:
      - cDNA(23-150)
      - UMI(12-19)
    find_pattern: ATTGCGCAATG
  file2:
    name: /path/to/bulk_RNA/bcl2fastq/fastqs/Undetermined_S0_R2_001.fastq.gz
    base_definition:
      - cDNA(1-150)
  file3:
    name: /path/to/bulk_RNA/bcl2fastq/fastqs/Undetermined_S0_I1_001.fastq.gz
    base_definition:
      - BC(1-8)
  file4:
    name: /path/to/bulk_RNA/bcl2fastq/fastqs/Undetermined_S0_I2_001.fastq.gz
    base_definition:
      - BC(1-8)
reference:
  STAR_index: /path/to/refdata-gex-GRCh38-2020-A/star/
  GTF_file: /path/to/refdata-gex-GRCh38-2020-A/genes/genes.gtf
  additional_STAR_params: '--clip3pAdapterSeq CTGTCTCTTATACACATCT'
out_dir: /path/to/bulk_RNA/zUMIs
num_threads: 20
mem_limit: 128
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 2
    phred: 20
barcodes:
  barcode_num: 18
  barcode_file: 
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 50000000
  demultiplex: no
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  write_ham: no
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
zUMIs_directory: /path/to/applications/zUMIs
```

Many fastqs are created in the merged.tmp directory, but there is no output at the end of the run, and I always see this in the error log:

`cat zUMIs.YAML.error.log`
```
$file1
NULL

$file2
NULL

$file3
NULL

$file4
NULL

[1] ""
[1] ""
[1] ""
[1] ""
[1] "" "" "" ""
[1] ""
[1] ""
[1] ""
[1] ""
[1] "" "" "" ""
[1] "NULL" "NULL" "NULL" "NULL"
$file1
NULL

$file2
NULL

$file3
NULL

$file4
NULL

$file1
NULL

$file2
NULL

$file3
NULL

$file4
NULL

[1]
```

Any idea what I could be doing wrong?

Thanks!
