### ISSUE TITLE
An error was encountered while running zUMIs(v2.9.7d) 

### ISSUE THREAD

**Issue by shangyf-stu** [sdparekh/zUMIs#352]
Hello,

Thanks for your useful tool, I have used zUMIs.2.9.4, and it works perfectly.
This data was sequenced by PLATEseq, and meet this error. I can't find the reason and have given the path permission.
Any help is appreciated！ 

Best wishes，
Shang

**To Reproduce**
```
project: dataset326
sequence_files:
  file1:
    name: /dataset326/filter_fastp/dataset326_clean_1.fastq.gz
    base_definition: 
      - BC(1-8)
      - cDNA(9-101)
  file2:
    name: /dataset326/filter_fastp/dataset326_clean_2.fastq.gz
    base_definition: 
      - BC(1-8)
      - cDNA(9-101)
reference:
  STAR_index: /zUMIs_v2.9.7d/star_index_2.7.3a_nogtf
  GTF_file: /3.2.0_star_index/Homo_sapiens.GRCh38.102.gtf
  exon_extension: no
  extension_length: 0
  scaffold_length_min: 0
  additional_files: 
  additional_STAR_params: 
out_dir: /dataset326/zUMIs
num_threads: 8
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: null
  barcode_file: null
  barcode_sharing: null
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: no
counting_opts:
  introns: yes
  intronProb: no
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  multi_overlap: no
  fraction_overlap: 0
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
```

**Screenshots**
```
/zUMIs_v2.9.7d/zUMIs/zUMIs.sh: line 171: dataset326.zUMIs_YAMLerror.log: Permission denied
tail: cannot open ‘dataset326.zUMIs_YAMLerror.log’ for reading: No such file or directory
sh: line 1:  1361 Killed                  STAR --readFilesCommand samtools view -@ 1 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /zUMIs_v2.9.7d/star_index_2.7.3a_nogtf --sjdbGTFfile /3.2.0_star_index/Homo_sapiens.GRCh38.102.gtf --runThreadN 7 --sjdbOverhang 92 --readFilesType SAM PE --twopassMode Basic --readFilesIn /dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326aa.filtered.tagged.bam,/dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326ab.filtered.tagged.bam,/dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326ac.filtered.tagged.bam,/dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326ad.filtered.tagged.bam,/dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326ae.filtered.tagged.bam,/dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326af.filtered.tagged.bam,/dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326ag.filtered.tagged.bam,/dataset326/zUMIs/zUMIs_output/.tmpMerge//dataset326.dataset326ah.filtered.tagged.bam --outFileNamePrefix /dataset326/zUMIs/dataset326.filtered.tagged.
Error in gsub("SN:", "", chr) : object 'chr' not found
Calls: .makeSAF ... .chromLengthFilter -> [ -> [.data.table -> eval -> eval -> gsub
In addition: Warning message:
In data.table::fread(bread, col.names = c("chr", "len"), header = F) :
  File '/tmp/Rtmp3H9sHq/file5786fdb3c39' has size 0. Returning a NULL data.table.
Execution halted
Loading required package: yaml
Loading required package: Matrix
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/dataset326/zUMIs/zUMIs_output/expression/dataset326.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/dataset326/zUMIs/zUMIs_output/expression/dataset326.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
```
