### ISSUE TITLE
test,help,

### ISSUE THREAD

**Issue by levinyi** [sdparekh/zUMIs#55]
hi, I'm trying to use your example dataset to run this pipeline, is this config file right?
```
###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

project: test

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI s                                                                                                                        equences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /cygene/work/01.zUMIS_test/barcoderead_HEK.1mio.fq.gz
    base_definition:
      BC(1-6) #example: BC(1-6)
      UMI(7-16) #example: UMI(7-16)
  file2:
    name: /cygene/work/01.zUMIS_test/cDNAread_HEK.1mio.fq.gz
    base_definition:
      cDNA(1-50) #example: cDNA(1-50)


#reference genome setup
reference:
  STAR_index: /cygene/work/refdata-cellranger-GRCh38-1.2.0/star/SAindex #path to STAR genome index
  GTF_file: /cygene/work/refdata-cellranger-GRCh38-1.2.0/genes/genes.gtf  #path to gene annotation file in GTF format
  # additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  # additional_STAR_params: #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: /cygene/work/01.zUMIS_test  #specify the full path to the output directory

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 6
mem_limit: null #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  BarcodeBinning: 0 #Hamming distance binning of close cell barcode sequences. ATTENTION! This option is currently no                                                                                                                        t implemented!
  nReadsperCell: 100 #Keep only the cell barcodes with atleast n number of reads.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desi                                                                                                                        red range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default                                                                                                                        : 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  velocyto: no #Would you like velocyto-compatible counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes


#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#below, the fqfilter will add a read_layout flag defining SE or PE
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
zUMIs_directory: /home/dushiyi/software/biosoftware/zUMIs
read_layout: PE
```
I only use Filtering,but when I type
```
sh /<mypath>/zUMIs-master.sh -y /<mypath>/zUMIs.yaml 
```
it shows a lot of errors:
```
/cygene/work/01.zUMIS_test/barcoderead_HEK.1mio.fq.gz /cygene/work/01.zUMIS_test/cDNAread_HEK.1mio.fq.gz


 You provided these parameters:
 YAML file:     /cygene/work/01.zUMIS_test/zUMIs.yaml
 zUMIs directory:               /home/dushiyi/software/biosoftware/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   null
 zUMIs version 2.0


Filtering...
Error in yaml.load(string, error.label = error.label, ...) :
  (/cygene/work/01.zUMIS_test/zUMIs.yaml) Parser error: while parsing a block mapping at line 16, column 5 did not find expected key at line 19, column 7
Calls: read_yaml -> yaml.load
Execution halted
Error in yaml.load(string, error.label = error.label, ...) :
  (/cygene/work/01.zUMIS_test/zUMIs.yaml) Parser error: while parsing a block mapping at line 16, column 5 did not find expected key at line 19, column 7
Calls: read_yaml -> yaml.load
Execution halted
Error in yaml.load(string, error.label = error.label, ...) :
  (/cygene/work/01.zUMIS_test/zUMIs.yaml) Parser error: while parsing a block mapping at line 16, column 5 did not find expected key at line 19, column 7
Calls: read_yaml -> yaml.load
Execution halted
Error in yaml.load(string, error.label = error.label, ...) :
  (/cygene/work/01.zUMIS_test/zUMIs.yaml) Parser error: while parsing a block mapping at line 16, column 5 did not find expected key at line 19, column 7
Calls: read_yaml -> yaml.load
Execution halted
sh: /zUMIs_output/.tmpMerge/.ae.filtered.tagged.bam: No such file or directory
sh: /zUMIs_output/.tmpMerge/.af.filtered.tagged.bam: No such file or directory
sh: /zUMIs_output/.tmpMerge/.ad.filtered.tagged.bam: No such file or directory
sh: /zUMIs_output/.tmpMerge/.ac.filtered.tagged.bam: No such file or directory
Error in yaml.load(string, error.label = error.label, ...) :
  (/cygene/work/01.zUMIS_test/zUMIs.yaml) Parser error: while parsing a block mapping at line 16, column 5 did not find expected key at line 19, column 7
Calls: read_yaml -> yaml.load
Execution halted
sh: /zUMIs_output/.tmpMerge/.ab.filtered.tagged.bam: No such file or directory
Error in yaml.load(string, error.label = error.label, ...) :
  (/cygene/work/01.zUMIS_test/zUMIs.yaml) Parser error: while parsing a block mapping at line 16, column 5 did not find expected key at line 19, column 7
Calls: read_yaml -> yaml.load
Execution halted
sh: /zUMIs_output/.tmpMerge/.aa.filtered.tagged.bam: No such file or directory
ls: cannot access /cygene/work/01.zUMIS_test/zUMIs_output/.tmpMerge//testdu.*.filtered.tagged.bam: No such file or directory
samtools merge: Invalid file list "/cygene/work/01.zUMIS_test/zUMIs_output/.tmpMerge//testdu.bamlist.txt"
samtools merge: You must specify at least one (and usually two or more) input files
Usage: samtools merge [-nurlf] [-h inh.sam] [-b <bamlist.fofn>] <out.bam> <in1.bam> [<in2.bam> ... <inN.bam>]

Options:
  -n         Input files are sorted by read name
  -t TAG     Input files are sorted by TAG value
  -r         Attach RG tag (inferred from file names)
  -u         Uncompressed BAM output
  -f         Overwrite the output BAM if exist
  -1         Compress level 1
  -l INT     Compression level, from 0 to 9 [-1]
  -R STR     Merge file in the specified region STR [all]
  -h FILE    Copy the header in FILE to <out.bam> [in1.bam]
  -c         Combine @RG headers with colliding IDs [alter IDs to be distinct]
  -p         Combine @PG headers with colliding IDs [alter IDs to be distinct]
  -s VALUE   Override random seed
  -b FILE    List of input BAM filenames, one per line [null]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
cat: /cygene/work/01.zUMIS_test/zUMIs_output/.tmpMerge//testdu.*.BCstats.txt: No such file or directory
Mapping...
Error in yaml.load(string, error.label = error.label, ...) :
  (/cygene/work/01.zUMIS_test/zUMIs.yaml) Parser error: while parsing a block mapping at line 16, column 5 did not find expected key at line 19, column 7
Calls: <Anonymous> -> yaml.load
Execution halted
Counting...
Error in file(file, "rt", encoding = fileEncoding) :
  cannot open the connection
Calls: read_yaml -> file
In addition: Warning message:
In file(file, "rt", encoding = fileEncoding) :
  cannot open file '/cygene/work/01.zUMIS_test/testdu.postmap.yaml': No such file or directory
Execution halted
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-08-19 21:56:31 EDT"
Error in file(file, "rt", encoding = fileEncoding) :
  cannot open the connection
Calls: read_yaml -> file
In addition: Warning message:
In file(file, "rt", encoding = fileEncoding) :
  cannot open file '/cygene/work/01.zUMIS_test/testdu.postmap.yaml': No such file or directory
Execution halted
```
