### ISSUE TITLE
Running Script Overwrites User's YAML File

### ISSUE THREAD

**Issue by DarioS** [sdparekh/zUMIs#68]
I have `STAR_exec: /savona/nobackup/biostat/software/STAR-2.6.1b/bin/STAR` in the YAML file. This is because I have STAR version 2.5.3 in the PATH variable for another project. However, when I run, `zUMIs-master.sh -y ./10XRNA.yaml` I notice that I get a warning in gedit "10XRNA.yaml changed on disk" and when I open it, I see that STAR_exec was changed to STAR.

Why does the running script modify the user's YAML file? It seems like bad software implementation to quietly modify a user's configuration file which means there's going to be an error message about readFilesType if the user runs the processing a second time. I can't find any documentation about the STAR_exec parameter, either.

It seems like my absolute path to STAR was accepted, though. I get different errors printed to the console, one for each read, instead.

```
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.
```

Looking at the head of the three FASTQ files, the read names appear to be in the same order, so this is unexpected. The definition I use is:

```
sequence_files:
  file1:
    name: hIPSC_scRNA_Sample1/hIPSC_scRNA_Sample1_R1.fastq.gz
    base_definition: cDNA(1-98)
  file2:
    name: hIPSC_scRNA_Sample1/hIPSC_scRNA_Sample1_R2.fastq.gz
    base_definition: BC(1-14)
  file3:
    name: hIPSC_scRNA_Sample1/hIPSC_scRNA_Sample1_R3.fastq.gz
    base_definition: UMI(1-10)
```

and the beginnings of the files are

```
$ gunzip -c hIPSC_scRNA_Sample1_R1.fastq.gz | head
@NS500239:144:H32MNBGXY:1:11101:22850:1046 1:N:0:NGCCGTTT
AAAAGNGGCGGAAAAGCTAGAAGCTCTATCGGTGAAGGAGGAGCCCAAGGAGGATGCTGAGGAGAAGCAATAAATCGTCTTATTTTATTTTCTTTGCC
+
/AAAA#/EEEEEEEEE/EEE///AEA</<E/EEEAEEEEE/EE/E/AEEEEEEEEEEEEEAEEEAAEEEAEEE/E/EEE/EEE/A<EEEEE//<E/</
@NS500239:144:H32MNBGXY:1:11101:21111:1047 1:N:0:CGCCGTTT
CTGAANTATTATAAGGTGGATGAGAATGGCAAAATTAGTCGCCTTCGTCGAGAGTGCCCTTCTGATGAATGTGGTGCTGGGGTGTTTATGGCAAGTCC
+
/AAAA#EEEAEEEAEEEEEEEEEEEEEEEEEEEAEE/EEAEE/EEA/EE/AEEE/A/<A<EEAEE6E/EAA<EA<EEEAEEEEA<66<AE<//A/<A/
@NS500239:144:H32MNBGXY:1:11101:14562:1049 1:N:0:CGCCGTTT
TGCTCNGAAATCTGTGGAGCAAACCACAGTTTCATGCCCATCGTCCTAGAATTAATTCCCCTAAAAATCTTTGAAATAGGGCACGTATTTACCCTATA

$ gunzip -c hIPSC_scRNA_Sample1_R2.fastq.gz | head
@NS500239:144:H32MNBGXY:1:11101:22850:1046 2:N:0:NGCCGTTT
ATGTACCTGATACC
+
//////6A////66
@NS500239:144:H32MNBGXY:1:11101:21111:1047 2:N:0:CGCCGTTT
GACCAAACTCAATC
+
//6///////////
@NS500239:144:H32MNBGXY:1:11101:14562:1049 2:N:0:CGCCGTTT
ACCTCGTGCCTCCA

$ gunzip -c hIPSC_scRNA_Sample1/hIPSC_scRNA_Sample1_R3.fastq.gz | head
@NS500239:144:H32MNBGXY:1:11101:22850:1046 3:N:0:NGCCGTTT
CAATATGATC
+
AAAAA/6<AA
@NS500239:144:H32MNBGXY:1:11101:21111:1047 3:N:0:CGCCGTTT
GTACCCAACC
+
A<AAAAAAA/
@NS500239:144:H32MNBGXY:1:11101:14562:1049 3:N:0:CGCCGTTT
CAATAGTCCG
```
