### ISSUE TITLE
error fread/samtools

### ISSUE THREAD

**Issue by ltosti** [sdparekh/zUMIs#78]
Hi there,

I performed DrocNc-seq and zUMI seems the ideal tool to analyze my intron-reach data. Unfortunately I have been trying to run zUMI for a couple of days but I get this error and I'm not sure what is causing it; here is the log:
```
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
Taking input= as a system command ('samtools view /mnt//lt88/zUMI_AFES1.filtered.tagged.bam | cut -f10 | head -n 100') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure envionment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.

EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "readFilesType" in input "Command-Line-Initial"
SOLUTION: use correct parameter name (check the manual)

Oct 05 15:28:02 ...... FATAL ERROR, exiting
Error in file(file, "rt") : cannot open the connection
Calls: .runFeatureCount -> <Anonymous> -> read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file './.Rsubread_featureCounts_pid57353': No such file or directory
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/mnt/lt88/zUMI/zUMIs_output/expression/zUMI_AFES1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
```

Any idea? Thank you for your help!

**Comment by sdparekh** [comment]
Hi,
to me it looks like you have read and write permission issues. Can you also share your YAML file and the command you are using.

Have you successfully installed all the dependencies as described here: https://github.com/sdparekh/zUMIs/wiki/Installation

**Comment by ltosti** [comment]
Hi, 
Thank you for your quick reply. 
I'm working on a cluster, CentOs 7.5.1804 with TORQUE job scheduler and all the dependencies were installed in a conda environment. This is my YAML file:

```
project: zUMI_AFES1
sequence_files:
  file1:
    name: /mnt/lt88/fastq/AFES448F1_S1_L001_R1_001.fastq.gz
    base_definition:
    - BC(1-16)
    - UMI(17-26)
  file2:
    name: /mnt/lt88/fastq/AFES448F1_S1_L001_R2_001.fastq.gz
    base_definition: cDNA(49)
reference:
  STAR_index: /mnt/lt88/STAR_transcriptome_zUMI
  GTF_file: /mnt/lt88/refdata-cellranger-hg19-1.2.0/genes/genes.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /mnt/lt88/zUMI
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: /mnt/lt88/zUMI_bc/barcodes.txt
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: no
  twoPass: yes
make_stats: yes
which_Stage: Filtering
```
