### ISSUE TITLE
sjdboverhang issue for 10x

### ISSUE THREAD

**Issue by mgood2** [sdparekh/zUMIs#84]
Hello,

I have one issue. I can't figure out if it is a zUMIs bug or wrong input. 

> EXITING because of fatal PARAMETERS error: present --sjdbOverhang=97 is not equal to the value at the genome generation step =100
> SOLUTION: 

so I changed my yaml to this below.
My yaml:
```
sequence_files:
  file1:
    name: /home2/warehouse/scRNAseq_10X_Mouse_Human_Tcell/fastq/F6_S1_L001_R1_001.fastq.gz
    base_definition:
    - BC(1-10)
    - UMI(11-26)
  file2:
    name: /home2/warehouse/scRNAseq_10X_Mouse_Human_Tcell/fastq/F6_S1_L001_R2_001.fastq.gz
    base_definition: cDNA(1-98)
reference:
  STAR_index: /opt/genomics/app/cellranger_refdata/GRCm38/GRCm38.91/star
  GTF_file: /opt/genomics/app/cellranger_refdata/GRCm38/GRCm38.91/genes/genes.gtf
  additional_STAR_params: --sjdbOverhang=100
  additional_files: ~
```

> EXITING: FATAL INPUT ERROR: duplicate parameter "sjdbOverhang" in input "Command-Line"
> SOLUTION: keep only one definition of input parameters in each input source
> 
> Oct 16 14:37:47 ...... FATAL ERROR, exiting

If you have any standard yaml for 10x protocol. could you share with me?

Thank you always for your help!
Eunmin
