### ISSUE TITLE
.tmpMerge empty (and minor issue)

### ISSUE THREAD

**Issue by RemyNicolle** [sdparekh/zUMIs#87]
Hi guys. Amazing repo, it's making my life so much easier.

I'm just running into a couple of problems

I've first got a minor issue for the example run with this error:
```R
Error in installed.packages()[grep("Rsubread", installed.packages()),  : 
  indice hors limites
```
That's the french for index out bound.

I corrected this in my runfeatureCountFUN.R file, it's only the grep that looking in the whole installed.packages() data.frame for Rsubread. It so happens that I have packages that depend on Rsubread so the string is located in some dependency column. Anyway, here's my fix:

runfeatureCountFUN.R @ line 12 replace `grep("Rsubread",installed.packages())` by `grep("Rsubread",installed.packages()[,1])`

After that correction, the whole thing runs like a charm for the example.

So that was my easy problem.

My other issue is when running on real data, I get this output:
```
Filtering...
Mapping...

EXITING because of FATAL INPUT ERROR: --readFilesType SAM requires specifying SE or PE reads
SOLUTION: specify --readFilesType SAM SE for single-end reads or --readFilesType SAM PE for paired-end reads
```
I've printed out the STAR launching cmd:
```
STAR --readFilesCommand  samtools  view -@2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype
 BAM Unsorted --genomeDir /datacit/00_DATABANKS/ensembl_91_humanMouseXenome/StarIndexed_GRC38_ensembl91_hgmmu_readLength100 --sjdbG
TFfile /datacit/00_DATABANKS/ensembl_91_humanMouseXenome/GRC38_hgmmu_chrename.gtf --runThreadN 8 --readFilesIn /datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.aa.filtered.tagged.bam,/datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.ab.filtered.tagged.bam,/datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.ac.filtered.tagged.bam,/datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.ad.filtered.tagged.bam,/datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.ae.filtered.tagged.bam,/datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.af.filtered.tagged.bam,/datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.ag.filtered.tagged.bam,/datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/zUMIs_output/.tmpMerge//BC-0078_S1.ah.filtered.tagged.bam --outFileNamePrefix /datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed/BC-0078_S1.filtered.tagged. --sjdbOverhang 66 --readFilesType SAM SE /datacit/00_DATABANKS/ensembl_91_humanMouseXenome/GRC38_hgmmu_chrename.fa
```
Which contains the `--readFilesType SAM SE` argument.

However, the .tmpMerge directory is empty.

Here is the yaml obtained through the shiny interface:
```
project: BC-0078_S1
sequence_files:
  file1:
    name: /datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/01_Raw_files/BC-0078_S1_R1.fastq.gz
    base_definition: cDNA(1-68)
  file2:
    name: /datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/01_Raw_files/BC-0078_S1_R2.fastq.gz
    base_definition:
    - BC(11-95)
    - UMI(1-10)
reference:
  STAR_index: /datacit/00_DATABANKS/ensembl_91_humanMouseXenome/StarIndexed_GRC38_ensembl91_hgmmu_readLength100
  GTF_file: /datacit/00_DATABANKS/ensembl_91_humanMouseXenome/GRC38_hgmmu_chrename.gtf
  additional_STAR_params: /datacit/00_DATABANKS/ensembl_91_humanMouseXenome/GRC38_hgmmu_chrename.fa
  additional_files: ~
out_dir: /datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Data/Experiment_data/RNA_seq/04_Processed
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 3
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
zUMIs_directory: /datacit/01_PROJECTS/CIT_PILOTS/PILOT_EXPERIMENTS/Test_RNAseq_singlecell/Analysis/remyzumi
read_layout: SE

```

What am I doing wrong?

Thanks for your help
